slownik_PL_DE = {
    "cześć": "Hallo",
    "jabłko": "Apfel",
    "jajecznica": "Rührei",
    "dzień": "Tag",
    "noc": "Nacht",
    "czas bożonarodzeniowy": "Weihnachtszeit",
    "mleko": "Milch",
    "kremówka": "Sahnekeks",
    "woda": "Wasser",
    "jeden": "eins",
    "pierwszy": "ersten",
    "kochać": "lieben",
    "ja": "ich",
    "ty": "du",
    "on": "er",
    "ona": "sie",
    "ono": "es",
    "my": "wir",
    "wy": "ihr",
    "oni": "sie",
    "śnieg": "Schnee",
    "słońce": "Sonne",
    "ser": "Käse",
    "piłka": "Ball",
    "kot": "Katze",
    "pies": "Hund",
    "spać": "schlafen",
    "jeść": "essen",
    "zimno": "kalt",
    "ciepło": "warm"
}

print(slownik_PL_DE[input()])