slownik_POL_HISZP = {
    "cześć": "Hallo",
    "jabłko": "Apfel",
    "jajecznica": "Rührei",
    "dzień": "Tag",
    "noc": "Nacht",
    "czas bożonarodzeniowy": "Weihnachtszeit",
    "mleko": "Milch",
    "kremówka": "Sahnekeks",
    "woda": "Wasser",
    "jeden": "eins",
    "pierwszy": "ersten",
    "kochać": "lieben",
    "ja": "ich",
    "ty": "du",
    "on": "er",
    "ona": "sie",
    "ono": "es",
    "my": "wir",
    "wy": "ihr",
    "oni": "sie"
    "jeden": "eins",
    "pierwszy": "ersten",
    "kochać": "lieben",
    "ja": "ich",
    "ty": "du",
    "on": "er",
    "ona": "sie",
    "ono": "es",
    "my": "wir",
    "wy": "ihr",
    "oni": "sie"
}

print(slownik_POL_HISZP[input()])