slownik_PL_FR = {
    "cześć": "Salut",
    "jabłko": "Pomme",
    "jajecznica": "Omelette",
    "dzień": "Jour",
    "noc": "Nuit",
    "czas bożonarodzeniowy": "Période de Noël",
    "mleko": "Lait",
    "kremówka": "Gâteau à la crème",
    "woda": "Eau",
    "jeden": "un",
    "pierwszy": "premier",
    "kochać": "aimer",
    "ja": "moi",
    "ty": "toi",
    "on": "lui",
    "ona": "elle",
    "ono": "celui-ci",
    "my": "nous",
    "wy": "vous",
    "oni": "eux",
    "dwa": "deux",
    "trzy": "trois",
    "cztery": "quatre",
    "pięć": "cuire",
    "sześć": "six",
    "siedem": "sept",
    "osiem": "huit",
    "dziewięć": "neuf",
    "dziesięć": "dix",
    "jedenaście": "onze",
    "dwanaście": "douze",
    "dwadzieścia": "vingt",
    "trzydzieści": "trente",
    "czterdzieści": "quarante",
    "pięćdziesiąt": "cinquante",
    "sześćdziesiąt": "soixante",
    "siedemdziesiąt": "soixante-dix",
    "osiemdziesiąt": "quatre-vingt",
    "dziewięćdziesiąt": "quatre-vingt-dix",
    "sto": "cent"
}

print(slownik_PL_FR[input()])
