slownik_PL_DE = {
    "cześć": "Hallo",
    "jabłko": "Apfel",
    "jajecznica": "Rührei",
    "dzień": "Tag",
    "noc": "Nacht",
    "czas bożonarodzeniowy": "Weihnachtszeit",
    "mleko": "Milch",
    "kremówka": "Sahnekeks",
    "woda": "Wasser",
    "jeden": "eins",
    "pierwszy": "ersten",
    "kochać": "lieben",
    "ja": "ich",
    "ty": "du",
    "on": "er",
    "ona": "sie",
    "ono": "es",
    "my": "wir",
    "wy": "ihr",
    "oni": "sie",
    "śnieg": "Schnee",
    "słońce": "Sonne",
    "ser": "Käse",
    "piłka": "Ball",
    "kot": "Katze",
    "pies": "Hund",
    "spać": "schlafen",
    "jeść": "essen",
    "zimno": "kalt",
    "ciepło": "warm"
    "dwa": "zwei",
    "trzy": "drei",
    "cztery": "vier",
    "pięć": "fünf",
    "sześć": "sechs",
    "siedem": "sieben",
    "osiem": "acht",
    "dziewięć": "neun",
    "dziesięć": "zehn",
    "jedenaście": "elf",
    "dwanaście": "zwölf",
    "dwadzieścia": "Zweifach",
    "trzydzieści": "dreißig",
    "czterdzieści": "vierzig",
    "pięćdziesiąt": "fünfzig",
    "sześćdziesiąt": "Sechzig",
    "siedemdziesiąt": "siebzig",
    "osiemdziesiąt": "achtzig",
    "dziewięćdziesiąt": "neunzig",
    "sto": "einhundert"
}

print(slownik_PL_DE[input()])